version: '3'
services:
  estore:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/python_estore
    environment:
      FLASK_ENV: development
    depends_on:
      - postgres
    restart: on-failure
  postgres:
      image: postgres
      restart: always
      volumes:
        - /var/lib/postgresql/data
      environment:
        - POSTGRES_USER=${USER}
        - POSTGRES_PASSWORD=${PASSWORD}
        - POSTGRES_DB=${DB}
      ports:
        - "5432:5432"